#!/bin/bash -exu
# use https://github.com/purarue/darker_errors
# to generate dark-themed error pages as fallbacks

recreate() {
	rm -rf "$1"
	mkdir -p "$1"
}

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
TARGET_DIR="${THIS_DIR}/lib/glue_web/templates/error"
TMP_DIR='/tmp/darker_temp'

recreate "${TMP_DIR}"
recreate "${TARGET_DIR}"

darker_errors -output-dir "${TMP_DIR}" '404:ERROR_AFTER_MSG:<p>Click <a href="https://purarue.xyz">here</a> to go back home.</p>' 'ERROR_TITLE:purarue - STATUS_MSG'

# minify HTML
html-minifier --minify-css --minify-js --remove-comments --remove-empty-attributes --remove-tag-whitespace --input-dir "${TMP_DIR}" --output-dir "${TARGET_DIR}" --file-ext html

# rename files
find "${TARGET_DIR}" -type f -exec mv {} {}.heex \;
