#!/usr/bin/env bash
# use https://github.com/purarue/wca_userinfo
# to fetch my wca results
# save it to a file and sync it to the remote dir
#
# this runs every few weeks by a block in my
# https://purarue.xyz/d/.local/scripts/linux/housekeeping?dark

set -e
set -o pipefail

wait-for-internet

echo 'Updating cubing record file...'

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

havecmd wca_userinfo || cargo install --git "https://github.com/purarue/wca_userinfo"

if [[ -z "$WCA_USER_ID" ]]; then
	echo 'WCA_USER_ID environment variable is not set' >&2
	exit 1
fi


mkdir -p ./data
wca_userinfo "$WCA_USER_ID" | jq >./data/cubing.json
scp ./data/cubing.json vultr:~/code/glue/data/
